"use client";

import type { CompareResponse, FieldDefinition, SchemaResponse } from "../lib/contracts";
import { attribute, money, unitPrice } from "../lib/client/display";
import { buildFamilyLayout, familyLabel } from "../lib/client/families";
import { ErrorState, Icon, Loading } from "./Icons";
import { HelpTip } from "./HelpTip";
import { FamilyCoverageSummary, FamilyHeader, TraitValue, familyStyle, type ColumnSettings } from "./TraitMatrix";

interface Props {
  data: CompareResponse | null; loading: boolean; error: string | null; onRetry: () => void;
  fields: FieldDefinition[]; schema: SchemaResponse; settings: ColumnSettings; onSettings: (settings: ColumnSettings) => void;
  onPin: (key: string) => void; activeFamily?: string | null; onFocusFamily?: (group: string | null) => void;
  ids: string[]; onRemove: (id: string) => void; onClear: () => void; onSelect: (id: string, field?: string) => void;
}

export function Comparison({ data, loading, error, onRetry, schema, settings, onSettings, onPin, activeFamily, onFocusFamily, ids, onRemove, onClear, onSelect }: Props) {
  const layout = buildFamilyLayout(schema.fields, schema.contract.groups, settings);
  function fieldRow(field: FieldDefinition) {
    return <tr key={field.key} className="comparison-trait-row" style={familyStyle(field.group)}><th scope="row"><div className="comparison-trait-label"><span>{field.label}</span><button className={`pin-button ${settings.pinned.includes(field.key) ? "is-pinned" : ""}`} onClick={() => onPin(field.key)} aria-label={`${settings.pinned.includes(field.key) ? "Unpin" : "Pin"} ${field.label}`} aria-pressed={settings.pinned.includes(field.key)}><Icon name="pin" size={12} /></button></div><small>{familyLabel(field.group)}{field.modelSelected ? " · pricing input" : ""}</small></th>{data?.products.map(product => <td key={product.id}><TraitValue value={attribute(product, field.key)} onClick={() => onSelect(product.id, field.key)} /><small>{attribute(product, field.key).reviewStatus.replaceAll("_", " ")}</small></td>)}</tr>;
  }
  return <section id="comparison" className="comparison panel family-comparison" aria-labelledby="comparison-title"><div className="section-heading"><div><p className="eyebrow"><span className="section-index">05</span> YOUR COMPARISON</p><div className="heading-with-help"><h2 id="comparison-title">A closer look, side by side.</h2><HelpTip label="About the shortlist"><p>Choose up to four source listings using the + buttons in the matrix. Your shortlist stays when cohort filters change.</p><p>Family expansion, trait search and pins are shared with the matrix. Family coverage counts every schema trait, including unknown, conflict and not applicable. Pinned traits appear once.</p><p>Shared traits alone do not establish like-for-like comparability. Select a value to inspect its evidence.</p></HelpTip></div></div><div className="comparison-actions"><span className="tag lilac">{ids.length} / 4 selected</span>{ids.length > 0 && <button className="text-button" onClick={onClear}>Clear shortlist</button>}</div></div>
    {ids.length === 0 ? <div className="comparison-empty"><div className="comparison-slots" aria-hidden="true">{[0, 1, 2, 3].map(index => <span key={index}><Icon name="plus" size={17} /></span>)}</div><div><h3>Your shortlist is empty.</h3></div></div> : <>
      <div className="comparison-family-guide"><span>{layout.families.length} families · {layout.visibleFields.length} open traits</span><a href="#trait-matrix" className="text-button">Adjust trait controls ↑</a></div>
      {loading && <Loading text="Loading your comparison…" />}{error && <ErrorState message={error} onRetry={onRetry} />}
      {data && <div className="table-scroll comparison-family-scroll" tabIndex={0} aria-label="Shortlisted source listings with expandable families; product names and unit prices stay visible while scrolling"><table className="comparison-table"><caption className="sr-only">Selected listings compared by schema family. Expand several families independently. Coverage always counts all traits in each family, including when trait searches or pricing-input filters are active. Pinned traits appear once.</caption><thead><tr><th scope="col">Product evidence<small>{layout.families.length} families · {layout.visibleFields.length} open traits</small></th>{data.products.map(product => <th key={product.id} scope="col"><div className="comparison-product"><button className="text-button product-title" onClick={() => onSelect(product.id)} title={product.name}>{product.name}</button><button className="icon-button" onClick={() => onRemove(product.id)} aria-label={`Remove ${product.name} from comparison`}><Icon name="close" size={14} /></button></div><small>{product.source}</small></th>)}</tr></thead>
        <tbody className="comparison-price-group"><tr className="comparison-price-row"><th scope="row">Observed unit price<small>£ /100 g · context unreviewed</small></th>{data.products.map(product => { const price = unitPrice(product); return <td key={product.id}><button className="comparison-price" onClick={() => onSelect(product.id)}>{price === null ? product.latestPriceConflict ? "Conflicting" : "Unavailable" : money(price)}</button></td>; })}</tr></tbody>
        {layout.pinned.length > 0 && <tbody className="comparison-pinned-group"><tr className="comparison-pinned-heading"><th scope="row" colSpan={data.products.length + 1}><span><Icon name="pin" size={13} />Pinned traits</span></th></tr>{layout.pinned.map(fieldRow)}</tbody>}
        {layout.families.map(family => <tbody key={family.key} className={`comparison-family-group ${activeFamily === family.key ? "family-active" : ""}`} style={familyStyle(family.key)}><tr className="comparison-family-heading"><th scope="row"><FamilyHeader compact family={family} settings={settings} onSettings={onSettings} activeFamily={activeFamily} onFocusFamily={onFocusFamily} /></th>{data.products.map(product => <td key={product.id}><FamilyCoverageSummary product={product} family={family} onSelect={onSelect} /></td>)}</tr>{family.visibleFields.map(fieldRow)}{family.expanded && family.visibleFields.length === 0 && <tr className="comparison-family-note"><td colSpan={data.products.length + 1}>{family.pinnedMatchingCount} matching traits pinned</td></tr>}{family.expanded && family.hiddenMatchingCount > 0 && <tr className="comparison-family-note"><td colSpan={data.products.length + 1}>{family.hiddenMatchingCount} more matching {family.label.toLowerCase()} traits. <button className="text-button" onClick={() => onSettings({ ...settings, limit: schema.fields.length })}>Show all traits in expanded families</button></td></tr>}</tbody>)}
        {layout.families.length === 0 && <tbody><tr className="comparison-family-note"><td colSpan={data.products.length + 1}>No matching families · {layout.pinned.length} pinned traits <button className="text-button" onClick={() => onSettings({ ...settings, group: "all", search: "", modelOnly: false })}>Reset trait controls</button></td></tr></tbody>}
      </table></div>}
    </>}
  </section>;
}
